# Generated by Django 3.2.22 on 2023-10-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_ip', models.CharField(blank=True, help_text='ip', max_length=64, null=True, verbose_name='ip')),
                ('demo_app_name', models.CharField(blank=True, help_text='应用名', max_length=32, null=True, verbose_name='应用名')),
                ('demo_status', models.CharField(blank=True, choices=[('Yes', '使用中'), ('No', '未使用')], help_text='状态', max_length=32, null=True, verbose_name='状态')),
                ('demo_describe', models.TextField(blank=True, help_text='使用描述', null=True, verbose_name='描述')),
                ('demo_Duration', models.BooleanField(default=False, help_text='时长', verbose_name='是否永久')),
                ('demo_allocation_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'DemoData',
                'verbose_name_plural': 'Demo数据管理',
                'ordering': ('demo_ip',),
            },
        ),
    ]
