# Generated by Django 3.2.22 on 2023-11-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo_model',
            name='demo_Duration',
            field=models.BooleanField(default=False, help_text='是否永久', verbose_name='是否永久'),
        ),
    ]
